### ISSUE TITLE
Default port and code error. (Nov 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/the-big-minecraft-piano#8]
Thanks for this tutorial (using it for experimenting mixing lights and loops, rather than Minecraft, but it's super helpful)! A couple of potential bug fixes to get it working: the default port for Sonic Pi seems to be 4560, and I needed to add a * after '/osc' on the previous page to get sound to come through: https://sonic-pi.net/tutorial.html#section-12-1 . Hope this is helpful!

URL: /en/projects/the-big-minecraft-piano/4

**Comment by libxx1** [comment]
@MarcScott hiya, do you know if this should be changed? 
We have port 4559 rather than 4560. 
We have ... note = sync "/osc/play_this" rather than note = sync "/osc*/play_this"

I can do the updating just wondered if you knew the correct code in each case.

**Comment by MarcScott** [comment]
Yep, looking at the SonicPi documentation, this would be the correct way to do it.
